__include__: [
  '../dataset/coco_detection_visdrone.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

output_dir: ./output/sfc_detr_r50vd_6x_coco
